version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    container_name: my-mongodb
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
